{
  "contest": 218,
  "handle": "apvlki",
  "risk": "2",
  "title": "MaxFailedAttempt is not properly enforced when calling `retry() ` after failed calls in RNSourceController.sol",
  "issueId": 434,
  "issueUrl": "https://github.com/code-423n4/2023-03-wenwin-findings/issues/434"
}